<a href="https://colab.research.google.com/github/mrbruce778/221/blob/Graph_algorithm/Assignment_on_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install GEOparse

Requirement already satisfied: GEOparse in /usr/local/lib/python3.12/dist-packages (2.0.4)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (2.0.2)
Requirement already satisfied: pandas>=0.17 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (2.2.2)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.17->GEOparse) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.17->GEOparse) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.17->GEOparse) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (2025.11.12)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.17->GEOparse) (1.17.0)

In [ ]:
import GEOparse
gse_id = 'GSE309664'
gse = GEOparse.get_GEO(geo=gse_id, destdir="./", silent=True)
print(f"Successfully loaded GEO Series: {gse.name}")

Successfully loaded GEO Series: GSE309664

In [ ]:
import pandas as pd
import urllib.request
import gzip

url = "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE309nnn/GSE309664/suppl/GSE309664_counts.txt.gz"
filename = "GSE309664_counts.txt.gz"


print(f"Downloading {filename}...")
urllib.request.urlretrieve(url, filename)
print("Download complete.")

expression_df = pd.read_csv(filename, sep='\t', index_col=0)

print(f"\nSUCCESS! Expression matrix shape: {expression_df.shape}")
print("\nFirst few rows:")
print(expression_df.head())

Downloading GSE309664_counts.txt.gz...
Download complete.

SUCCESS! Expression matrix shape: (44567, 40)

First few rows:
           Sample_NT2-p0-1  Sample_NT2-p0-10  Sample_NT2-p0-2  \
5S_rRNA               0.00              0.00             0.00
5_8S_rRNA             0.00              0.00             0.00
7SK                  93.52             81.77           150.18
A1BG                 19.42             50.54            25.56
A1BG-AS1             20.88             55.84            60.49

           Sample_NT2-p0-3  Sample_NT2-p0-4  Sample_NT2-p0-5  Sample_NT2-p0-6  \
5S_rRNA               0.00             0.00             0.00             0.00
5_8S_rRNA             0.00             0.00             0.00             0.00
7SK                 106.03            96.76           111.65           157.46
A1BG                 22.42            33.85            27.46            17.03
A1BG-AS1             55.07            57.83            47.99            34.56

           Sample_NT2-p0-7  Sample_NT2-p0-8  Sample_NT2-p0-9  ...  \
5S_rRNA               0.00             0.00             0.00  ...
5_8S_rRNA             0.00             0.00             0.00  ...
7SK                  65.75            86.46            94.08  ...
A1BG                 52.48            54.71            48.79  ...
A1BG-AS1             60.27            43.96            41.84  ...

           Sample_SY5Y-WT-1  Sample_SY5Y-WT-10  Sample_SY5Y-WT-2  \
5S_rRNA                0.00               0.00              0.00
5_8S_rRNA              0.00               0.00              0.00
7SK                   25.43              15.77             28.58
A1BG                 145.64             132.17            162.60
A1BG-AS1             164.44             183.39            226.51

           Sample_SY5Y-WT-3  Sample_SY5Y-WT-4  Sample_SY5Y-WT-5  \
5S_rRNA                0.00              0.00              0.00
5_8S_rRNA              0.00              0.00              0.00
7SK                   31.30             30.00             35.50
A1BG                 145.94            140.98            135.91
A1BG-AS1             194.12            197.19            204.20

           Sample_SY5Y-WT-6  Sample_SY5Y-WT-7  Sample_SY5Y-WT-8  \
5S_rRNA                0.00              0.00              0.00
5_8S_rRNA              0.00              0.00              0.00
7SK                   32.35             25.85             32.24
A1BG                 119.21            128.87            147.41
A1BG-AS1             177.91            192.62            185.50

           Sample_SY5Y-WT-9
5S_rRNA                0.00
5_8S_rRNA              0.00
7SK                   30.63
A1BG                 167.80
A1BG-AS1             165.09

[5 rows x 40 columns]

In [ ]:

expression_df.to_csv('GSE309664_Expression_Matrix.tsv', sep='\t', index=True)
print("\n Expression data saved as: GSE309664_Expression_Matrix.tsv")

 Expression data saved as: GSE309664_Expression_Matrix.tsv

In [ ]:
filename = "GSE309664_Expression_Matrix.tsv"
loaded_expression_df  = pd.read_csv(filename,sep = '\t',index_col =0)

loaded_expression_df.head()

,Sample_NT2-p0-1,Sample_NT2-p0-10,Sample_NT2-p0-2,Sample_NT2-p0-3,Sample_NT2-p0-4,Sample_NT2-p0-5,Sample_NT2-p0-6,Sample_NT2-p0-7,Sample_NT2-p0-8,Sample_NT2-p0-9,...,Sample_SY5Y-WT-1,Sample_SY5Y-WT-10,Sample_SY5Y-WT-2,Sample_SY5Y-WT-3,Sample_SY5Y-WT-4,Sample_SY5Y-WT-5,Sample_SY5Y-WT-6,Sample_SY5Y-WT-7,Sample_SY5Y-WT-8,Sample_SY5Y-WT-9
5S_rRNA,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5_8S_rRNA,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7SK,93.52,81.77,150.18,106.03,96.76,111.65,157.46,65.75,86.46,94.08,...,25.43,15.77,28.58,31.30,30.00,35.50,32.35,25.85,32.24,30.63
A1BG,19.42,50.54,25.56,22.42,33.85,27.46,17.03,52.48,54.71,48.79,...,145.64,132.17,162.60,145.94,140.98,135.91,119.21,128.87,147.41,167.80
A1BG-AS1,20.88,55.84,60.49,55.07,57.83,47.99,34.56,60.27,43.96,41.84,...,164.44,183.39,226.51,194.12,197.19,204.20,177.91,192.62,185.50,165.09

In [ ]:
X_data = expression_df.T

In [ ]:
X_data.head()

,5S_rRNA,5_8S_rRNA,7SK,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,...,snoU18,snoU2-30,snoU2_19,snoU83B,snoZ196,snoZ278,snoZ40,snoZ6,snosnR66,uc_338
Sample_NT2-p0-1,0.0,0.0,93.52,19.42,20.88,0.0,29.00,16.00,73.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.00
Sample_NT2-p0-10,0.0,0.0,81.77,50.54,55.84,0.0,7.00,8.00,66.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.62
Sample_NT2-p0-2,0.0,0.0,150.18,25.56,60.49,1.0,103.89,23.11,115.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.61
Sample_NT2-p0-3,0.0,0.0,106.03,22.42,55.07,1.0,60.00,19.00,110.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.13
Sample_NT2-p0-4,0.0,0.0,96.76,33.85,57.83,0.0,73.93,23.07,96.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_data)

In [ ]:

from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)
principal_components = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(data = principal_components)


print(f"Original dimension (Genes): {X_scaled.shape[1]}")
print(f"Reduced dimension (PCs needed for 95% variance): {pca.n_components_}")
print(f"Total variance explained: {pca.explained_variance_ratio_.sum():.4f}")

Original dimension (Genes): 44567
Reduced dimension (PCs needed for 95% variance): 33
Total variance explained: 0.9512

In [ ]:
loadings_matrix = pca.components_

loadings_df = pd.DataFrame(
    data=loadings_matrix.T,
    index=X_data.columns,
    columns=[f'PC{i+1}' for i in range(pca.n_components_)]
)

print(f" Loadings DataFrame created with shape: {loadings_df.shape}")
print("\nLoadings Head (First 5 Genes across PC1-PC5):")
print(loadings_df.iloc[:, :5].head())

 Loadings DataFrame created with shape: (44567, 33)

Loadings Head (First 5 Genes across PC1-PC5):
                    PC1           PC2           PC3           PC4  \
5S_rRNA    1.696290e-03  3.748852e-03 -8.098348e-04  3.996354e-03
5_8S_rRNA -1.533264e-15 -5.068733e-16 -5.026671e-16 -1.782188e-15
7SK       -8.051931e-03  7.579323e-03  1.626169e-03  3.201828e-03
A1BG       9.838643e-03 -1.756995e-04 -1.357000e-03  1.609710e-03
A1BG-AS1   9.673920e-03 -8.387510e-04  2.380830e-03  3.096072e-03

                    PC5
5S_rRNA    3.461266e-03
5_8S_rRNA  2.379978e-15
7SK        4.993619e-05
A1BG       1.419113e-03
A1BG-AS1   3.452965e-03

In [ ]:
print(principal_components[0])

[ -75.24274607   21.77686152   16.08861301 -181.25075848  -33.15460693
  -33.4891858     1.3499715    -9.82811159  -27.87725074   -9.32673957
   -7.04280339    5.44606096  -12.85255816   12.52724223  -12.70775603
   -1.73695675   -9.25939775   -9.01607842   -5.00595313    2.22183932
  -20.41192181  -19.37692989    2.77393587   -3.53470839  -10.50283683
  -10.13449428   -3.84566133  -14.3287092     3.14690007   -1.98929577
   15.46183533  -21.53580665    2.08573436]

In [ ]:

top_5_loadings_df = loadings_df.iloc[:, :5]

variance_ratios = pca.explained_variance_ratio_
variance_series = pd.Series(
    variance_ratios[:5],
    index=[f'PC{i+1}' for i in range(5)]
)

abs_loadings = top_5_loadings_df.abs()

weighted_abs_loadings = abs_loadings.mul(variance_series, axis='columns')

weighted_score = weighted_abs_loadings.sum(axis=1)


top_20_weighted_genes = weighted_score.sort_values(ascending=False).head(20)

print("--- Top 20 Genes Based on Overall Weighted Influence (PC1-PC5) ---")
print(top_20_weighted_genes)

--- Top 20 Genes Based on Overall Weighted Influence (PC1-PC5) ---
CD9        0.004444
SP1        0.004436
THUMPD1    0.004431
DEAF1      0.004428
MTMR12     0.004427
MPDZ       0.004425
NAA50      0.004423
PRIM1      0.004422
ERCC6L     0.004421
C9orf64    0.004420
STIP1      0.004420
TFDP1      0.004419
MRPS2      0.004418
ZC3H13     0.004418
PPAN       0.004418
CSE1L      0.004418
COASY      0.004417
USP10      0.004416
IPO5       0.004416
MED17      0.004416
dtype: float64

PCA_10

In [ ]:
loadings_matrix = pca.components_

loadings_df = pd.DataFrame(
    data=loadings_matrix.T,
    index=X_data.columns,
    columns=[f'PC{i+1}' for i in range(pca.n_components_)]
)

print(f" Loadings DataFrame created with shape: {loadings_df.shape}")
print("\nLoadings Head (First 5 Genes across PC1-PC10):")
print(loadings_df.iloc[:, :10].head())

In [ ]:

top_5_loadings_df = loadings_df.iloc[:, :10]

variance_ratios = pca.explained_variance_ratio_
variance_series = pd.Series(
    variance_ratios[:10],
    index=[f'PC{i+1}' for i in range(10)]
)

abs_loadings = top_5_loadings_df.abs()

weighted_abs_loadings = abs_loadings.mul(variance_series, axis='columns')

weighted_score = weighted_abs_loadings.sum(axis=1)

top_20_weighted_genes = weighted_score.sort_values(ascending=False).head(20)

print("--- Top 20 Genes Based on Overall Weighted Influence (PC1-PC5) ---")
print(top_20_weighted_genes)

We can see that the plot with 10 principal components shows higher gene loading values compared to the one with 5 principal components. This happens because the original gene expression data (containing ~95% variance) was reduced into 33 principal components, meaning these components retain most of the informational structure of the dataset.

When we select only the first 5 PCs, we capture a smaller portion of this variance. Since the earliest PCs explain the most variation, choosing just 5 means we are working with a more compressed representation of the data. However, when we increase the selection to 10 PCs, we include more information from the dataset — so the overall contribution of genes becomes larger.

In PCA, loadings represent how much each gene contributes to a given principal component. Therefore, when we include more PCs, the total contribution values of genes increase, which is why the second list shows larger numbers than the first.

Using PCA for gene selection can be useful, but it has both strengths and limitations. PCA helps reduce dimensionality by transforming thousands of genes into a smaller number of principal components that capture the largest proportion of variance in the data. This is effective for identifying major expression patterns and removing noise, making downstream analysis faster and more manageable. Selecting genes based on high loadings can therefore highlight those that contribute strongly to the major sources of variance in the dataset.